### ISSUE TITLE
Is this a main fork?

### ISSUE THREAD

**Issue by koizumistr** [devrimgunduz/postgresql-plruby#2]
Can I assume this as a main fork?
If so
- can I write this URL in PostgreSQL Documentation?
- can I send pull request to this fork?

Or should I make a new "organization" (ex. pg-plruby-user-group) on GitHub and merge all forks from knu's?

**Comment by devrimgunduz** [comment]
Hi,

Very apologies for the late response. This is a fork that aims to survive the project. I'm just the RPM packager, so any patches welcome!

**Comment by praiskup** [comment]
> Can I assume this as a main fork?

We'd like to make plruby working again here at least, but saying "this is the main fork" would be too hard statement, are there any other forks?  Let's see how it works, @koizumistr would you mind sending some patches?  I'm starting in #3.

> can I write this URL in PostgreSQL Documentation?

Why not.

> can I send pull request to this fork?

Sure!

**Comment by jeltz** [comment]
@koizumistr has a fork at https://github.com/pg-plruby-ug/postgresql-plruby which seems to have more commits.

**Comment by praiskup** [comment]
Indeed, many of the things from #3 are done there, too.  I'd be especially interested in testsuite fixes (if they are fixed), but I can not build that fork.
